# Generated by Django 4.2.9 on 2024-11-17 19:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.JSONField()),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_range_min', models.IntegerField()),
                ('score_range_max', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', wagtail.fields.RichTextField()),
                ('action_items', models.JSONField()),
                ('resources', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.category')),
            ],
        ),
    ]
