version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=yourdbuser
      - POSTGRES_PASSWORD=yourdbpassword

  ml-service:
    build: 
      context: ./ml_service
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/your_model.pkl

volumes:
  postgres_data: