# Generated by Django 5.1.3 on 2024-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
