# Generated by Django 4.2.9 on 2024-11-18 16:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('hero_cta_text', models.CharField(default='Start Assessment', max_length=100)),
                ('hero_cta_link', models.URLField(default='/assessment/start/')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('feature_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('features', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='Font Awesome class name')), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())])))])), ('testimonial', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock()), ('role', wagtail.blocks.CharBlock())]))], use_json_field=True)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
